// Generated by CoffeeScript 2.7.0
var from;

from = {
  user: "sender email",
  password: "app password for sender email",
  host: "smtp.gmail.com",
  port: 465,
  ssl: true,
  to: "receiver email",
  title: "A job has just been done"
};

exports._from = from

